version: "3.7"
services:
  homepage:
    build:
      context: ../
      dockerfile: ./website/homepage/Dockerfile
      args: 
          COLAB_NOTEBOOK_LINKS: $COLAB_NOTEBOOK_LINKS
    container_name: homepage
    ports:
      - "8080:80"
  demos:
    build:
      context: ../
      dockerfile: ./website/demos/Dockerfile
    container_name: demos
    ports:
      - "8070:80"
